#开发环境
spring:
  datasource:
    name: moe_classroom_manager
    username: root
    password: 1234
    url: jdbc:mysql://127.0.0.1:3306/moe_classroom_manager?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true
server:
  port: 81

upload:
  prefix: http://127.0.0.1
  path: D:\Dev\MoeClassroomManager\Upload\
