name: Lint & Format Code

on:
  workflow_dispatch: ~
  push:
    paths:
      - "src/main/**.java"
    branches:
      - "master"

jobs:
  Format-Code:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Restore cached Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Format code
        run: mvn formatter:format

      - run: git config --global user.name "github-actions"
      - run: git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: git stash
      - run: git checkout ${{ steps.extract_branch.outputs.branch }} && git pull
      - run: git stash pop || true

      - name: Commit code changes
        run: git add -u && git commit -m 'Format code [skip ci]' || true
      - name: Push code changes
        run: git push --set-upstream --force origin ${{ steps.extract_branch.outputs.branch }}
